name: Jest + SonarCloud - NodeJS CI

on:
  push:
    branches: 
      - '**'        # todas as branches
      - '!documentacao'   # exceto documentacao

  pull_request:
    branches: 
      - '**'        # todas as branches
      - '!documentacao'   # exceto documentacao

defaults:
  run:
    working-directory: api

jobs:

  build:
    runs-on: ubuntu-latest
    container: node:14

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Create Database
        run: npx sequelize db:create

      - name: Migrate Database
        run: npx sequelize db:migrate

      - name: Run Tests
        run: npm test

        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432